export const ADD_PRODUCT = 'ADD_PRODUCT'

export const ADD_CARTLIST = 'ADD_CARTLIST'

export const GET_CARTLIST = 'GET_CARTLIST'

export const DELETE_CARTLIST = 'DELETE_CARTLIST'

export const GET_PRODUCT = 'GET_PRODUCT'

export const UPDATE_CONTENT = 'UPDATE_CONTENT'

export const DELETE_PORDUCT = 'DELETE_PORDUCT'

export const UPDATE_PORDUCT = 'UPDATE_PORDUCT'

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'

// category

export const GET_CATEGORY = 'GET_CATEGORY'

export const ADD_CATEGORY = 'ADD_CATEGORY'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

// subcategory

export const GET_SUBCATEGORY = 'GET_SUBCATEGORY'

export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY'

export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY'

export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY'
